######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 5 21:28:56 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += Whim.h CodeEditor.h Highlighter.h MainWindow.h CodeDock.h
SOURCES += Whim.cpp CodeEditor.cpp Highlighter.cpp main.cpp MainWindow.cpp CodeDock.cpp
