######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 5 21:28:56 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += CodeEditor.h Highlighter.h MainWindow.h
SOURCES += CodeEditor.cpp Highlighter.cpp main.cpp MainWindow.cpp
